services:
  database:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data_match_making:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - match-making-net

  backend:
    build: ./server
    container_name: backend
    restart: always
    env_file:
      - ./server/.env
    expose:
      - "8080"
    networks:
      - match-making-net

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: frontend
    volumes:
      - frontend_dist:/match-making/dist
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_dist:/usr/share/nginx/html:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - match-making-net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - match-making-net

volumes:
  postgres_data_match_making:
    name: postgres_data_match_making
  frontend_dist:

networks:
  match-making-net:
    driver: bridge