name: Java-React Continuous Integration

on:
  push:
    branches: ["**"]

  pull_request:
    branches: [main]

jobs:

  lint:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java-version: [21]
        node-version: [20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make mvnw executable
        run: chmod +x app/server/mvnw

      # Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: maven

      # Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: app/client/package-lock.json

      - name: Install frontend dependencies
        working-directory: app/client
        run: npm ci

      - name: Lint frontend
        working-directory: app/client
        run: npm run lint --max-warnings=0

      - name: Lint backend
        working-directory: app/server
        run: ./mvnw checkstyle:check

  build:
    needs: lint
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java-version: [21]
        node-version: [20]

    steps:
      - uses: actions/checkout@v4

      - name: Make mvnw executable
        run: chmod +x app/server/mvnw

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: maven

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: app/client/package-lock.json

      - working-directory: app/client
        run: npm ci

      - working-directory: app/client
        run: npm run build

      - working-directory: app/server
        run: ./mvnw clean package -DskipTests

  test:
    needs: build
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java-version: [21]
        node-version: [20]

    steps:
      - uses: actions/checkout@v4

      - name: Make mvnw executable
        run: chmod +x app/server/mvnw

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: maven

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: app/client/package-lock.json

      - working-directory: app/client
        run: npm ci

      - working-directory: app/client
        run: npm test

      - working-directory: app/server
        run: ./mvnw test